/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.appleistocktestone;

import com.mycompany.appleistocktestone.Database.DatabaseManager;
import com.mycompany.appleistocktestone.Sevices.ProductService;
import com.mycompany.appleistocktestone.Sevices.UserService;
import javax.swing.JOptionPane;

/**
 *
 * @author Adithya
 */
public class ManagerForm extends javax.swing.JFrame {

    private final UserService userService;
    private final ProductService productService;
    public ManagerForm(UserService userService, ProductService productService) {
        initComponents();
        this.userService = userService;
        this.productService = productService;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        MbackgroundPanel = new javax.swing.JPanel();
        buttonPanel = new javax.swing.JPanel();
        btnTbProduct = new javax.swing.JButton();
        btnTbAddProduct = new javax.swing.JButton();
        btnTbUser = new javax.swing.JButton();
        btnTbProfile = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        managerDashboard = new javax.swing.JTabbedPane();
        crudProductPanel = new javax.swing.JPanel();
        addMainPanel = new javax.swing.JPanel();
        lblManageProduct = new javax.swing.JLabel();
        btnCashierView = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        productTable = new javax.swing.JTable();
        addPrduct = new javax.swing.JButton();
        removeProduct = new javax.swing.JButton();
        addPrduct2 = new javax.swing.JButton();
        userPanel = new javax.swing.JPanel();
        userMainPanel = new javax.swing.JPanel();
        lblManageUsers = new javax.swing.JLabel();
        btnAddUser = new javax.swing.JButton();
        profilePanel = new javax.swing.JPanel();
        userMainPanel1 = new javax.swing.JPanel();
        lblManageUsers1 = new javax.swing.JLabel();
        btnLogOut = new javax.swing.JButton();
        viewProductPanel = new javax.swing.JPanel();
        viewMainPanel = new javax.swing.JPanel();
        lblViewProductMain = new javax.swing.JLabel();
        btnViewTbAddProduct = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Manager Dashboard");
        setPreferredSize(new java.awt.Dimension(800, 700));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        MbackgroundPanel.setBackground(new java.awt.Color(255, 255, 255));
        MbackgroundPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnTbProduct.setBackground(new java.awt.Color(0, 0, 0));
        btnTbProduct.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnTbProduct.setForeground(new java.awt.Color(255, 255, 204));
        btnTbProduct.setText("Products");
        btnTbProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTbProductActionPerformed(evt);
            }
        });

        btnTbAddProduct.setBackground(new java.awt.Color(0, 0, 0));
        btnTbAddProduct.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnTbAddProduct.setForeground(new java.awt.Color(255, 255, 204));
        btnTbAddProduct.setText("Add Product");
        btnTbAddProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTbAddProductActionPerformed(evt);
            }
        });

        btnTbUser.setBackground(new java.awt.Color(0, 0, 0));
        btnTbUser.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnTbUser.setForeground(new java.awt.Color(255, 255, 204));
        btnTbUser.setText("Users");
        btnTbUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTbUserActionPerformed(evt);
            }
        });

        btnTbProfile.setBackground(new java.awt.Color(0, 0, 0));
        btnTbProfile.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnTbProfile.setForeground(new java.awt.Color(255, 255, 204));
        btnTbProfile.setText("My Profile");
        btnTbProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTbProfileActionPerformed(evt);
            }
        });

        btnLogout.setBackground(new java.awt.Color(0, 0, 0));
        btnLogout.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 204));
        btnLogout.setText("LogOut");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout buttonPanelLayout = new javax.swing.GroupLayout(buttonPanel);
        buttonPanel.setLayout(buttonPanelLayout);
        buttonPanelLayout.setHorizontalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTbAddProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTbProduct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTbUser, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTbProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        buttonPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnLogout, btnTbAddProduct, btnTbProfile, btnTbUser});

        buttonPanelLayout.setVerticalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelLayout.createSequentialGroup()
                .addGap(297, 297, 297)
                .addComponent(btnTbProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTbAddProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTbUser, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(btnTbProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(284, Short.MAX_VALUE))
        );

        buttonPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnLogout, btnTbAddProduct, btnTbUser});

        MbackgroundPanel.add(buttonPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 850));

        crudProductPanel.setBackground(new java.awt.Color(255, 255, 204));

        addMainPanel.setBackground(new java.awt.Color(0, 0, 0));

        lblManageProduct.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        lblManageProduct.setForeground(new java.awt.Color(255, 255, 204));
        lblManageProduct.setText("Manage Products");

        btnCashierView.setBackground(new java.awt.Color(255, 255, 204));
        btnCashierView.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnCashierView.setForeground(new java.awt.Color(0, 0, 0));
        btnCashierView.setText("View As Cashier");
        btnCashierView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCashierViewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addMainPanelLayout = new javax.swing.GroupLayout(addMainPanel);
        addMainPanel.setLayout(addMainPanelLayout);
        addMainPanelLayout.setHorizontalGroup(
            addMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addMainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblManageProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 219, Short.MAX_VALUE)
                .addComponent(btnCashierView)
                .addContainerGap())
        );
        addMainPanelLayout.setVerticalGroup(
            addMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addMainPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(addMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblManageProduct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCashierView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        productTable.setAutoCreateRowSorter(true);
        productTable.setBackground(new java.awt.Color(255, 255, 255));
        productTable.setForeground(new java.awt.Color(0, 0, 0));
        productTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ProductID", "Product Name", "Category", "Price", "QTY"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(productTable);
        if (productTable.getColumnModel().getColumnCount() > 0) {
            productTable.getColumnModel().getColumn(4).setResizable(false);
        }

        addPrduct.setBackground(new java.awt.Color(0, 0, 0));
        addPrduct.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        addPrduct.setForeground(new java.awt.Color(255, 255, 204));
        addPrduct.setText("Add");
        addPrduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPrductActionPerformed(evt);
            }
        });

        removeProduct.setBackground(new java.awt.Color(0, 0, 0));
        removeProduct.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        removeProduct.setForeground(new java.awt.Color(255, 255, 204));
        removeProduct.setText("Remove");

        addPrduct2.setBackground(new java.awt.Color(0, 0, 0));
        addPrduct2.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        addPrduct2.setForeground(new java.awt.Color(255, 255, 204));
        addPrduct2.setText("Update");

        javax.swing.GroupLayout crudProductPanelLayout = new javax.swing.GroupLayout(crudProductPanel);
        crudProductPanel.setLayout(crudProductPanelLayout);
        crudProductPanelLayout.setHorizontalGroup(
            crudProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(crudProductPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(crudProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addMainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(crudProductPanelLayout.createSequentialGroup()
                        .addComponent(addPrduct, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addPrduct2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(82, 82, 82)
                        .addComponent(removeProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        crudProductPanelLayout.setVerticalGroup(
            crudProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(crudProductPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addMainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(339, 339, 339)
                .addGroup(crudProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addPrduct, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addPrduct2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(removeProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(351, Short.MAX_VALUE))
        );

        managerDashboard.addTab("tab2", crudProductPanel);

        userPanel.setBackground(new java.awt.Color(255, 255, 204));

        userMainPanel.setBackground(new java.awt.Color(0, 0, 0));

        lblManageUsers.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        lblManageUsers.setForeground(new java.awt.Color(255, 255, 204));
        lblManageUsers.setText("Cashier Details");

        btnAddUser.setBackground(new java.awt.Color(255, 255, 204));
        btnAddUser.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnAddUser.setForeground(new java.awt.Color(0, 0, 0));
        btnAddUser.setText("Add Cashier");
        btnAddUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddUserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout userMainPanelLayout = new javax.swing.GroupLayout(userMainPanel);
        userMainPanel.setLayout(userMainPanelLayout);
        userMainPanelLayout.setHorizontalGroup(
            userMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userMainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblManageUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 244, Short.MAX_VALUE)
                .addComponent(btnAddUser)
                .addContainerGap())
        );
        userMainPanelLayout.setVerticalGroup(
            userMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userMainPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(userMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblManageUsers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAddUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout userPanelLayout = new javax.swing.GroupLayout(userPanel);
        userPanel.setLayout(userPanelLayout);
        userPanelLayout.setHorizontalGroup(
            userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(userMainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        userPanelLayout.setVerticalGroup(
            userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(userMainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(778, Short.MAX_VALUE))
        );

        managerDashboard.addTab("tab3", userPanel);

        profilePanel.setBackground(new java.awt.Color(255, 255, 204));

        userMainPanel1.setBackground(new java.awt.Color(0, 0, 0));

        lblManageUsers1.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        lblManageUsers1.setForeground(new java.awt.Color(255, 255, 204));
        lblManageUsers1.setText("My Profile");

        btnLogOut.setBackground(new java.awt.Color(255, 255, 204));
        btnLogOut.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnLogOut.setForeground(new java.awt.Color(0, 0, 0));
        btnLogOut.setText("LOGOUT");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout userMainPanel1Layout = new javax.swing.GroupLayout(userMainPanel1);
        userMainPanel1.setLayout(userMainPanel1Layout);
        userMainPanel1Layout.setHorizontalGroup(
            userMainPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userMainPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblManageUsers1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 350, Short.MAX_VALUE)
                .addComponent(btnLogOut)
                .addContainerGap())
        );
        userMainPanel1Layout.setVerticalGroup(
            userMainPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userMainPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(userMainPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblManageUsers1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLogOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout profilePanelLayout = new javax.swing.GroupLayout(profilePanel);
        profilePanel.setLayout(profilePanelLayout);
        profilePanelLayout.setHorizontalGroup(
            profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, profilePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(userMainPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        profilePanelLayout.setVerticalGroup(
            profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profilePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(userMainPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(778, Short.MAX_VALUE))
        );

        managerDashboard.addTab("tab4", profilePanel);

        viewProductPanel.setBackground(new java.awt.Color(255, 255, 204));

        viewMainPanel.setBackground(new java.awt.Color(0, 0, 0));

        lblViewProductMain.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        lblViewProductMain.setForeground(new java.awt.Color(255, 255, 204));
        lblViewProductMain.setText("View Products");

        btnViewTbAddProduct.setBackground(new java.awt.Color(255, 255, 204));
        btnViewTbAddProduct.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnViewTbAddProduct.setForeground(new java.awt.Color(0, 0, 0));
        btnViewTbAddProduct.setText("Add Product");
        btnViewTbAddProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewTbAddProductActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout viewMainPanelLayout = new javax.swing.GroupLayout(viewMainPanel);
        viewMainPanel.setLayout(viewMainPanelLayout);
        viewMainPanelLayout.setHorizontalGroup(
            viewMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewMainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblViewProductMain)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 295, Short.MAX_VALUE)
                .addComponent(btnViewTbAddProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        viewMainPanelLayout.setVerticalGroup(
            viewMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viewMainPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(viewMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblViewProductMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnViewTbAddProduct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout viewProductPanelLayout = new javax.swing.GroupLayout(viewProductPanel);
        viewProductPanel.setLayout(viewProductPanelLayout);
        viewProductPanelLayout.setHorizontalGroup(
            viewProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viewProductPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(viewMainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        viewProductPanelLayout.setVerticalGroup(
            viewProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewProductPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(viewMainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(778, Short.MAX_VALUE))
        );

        managerDashboard.addTab("tab1", viewProductPanel);

        MbackgroundPanel.add(managerDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, -20, 620, 870));

        getContentPane().add(MbackgroundPanel);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTbProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTbProductActionPerformed
        // Navigate Product5 View Tab
        managerDashboard.setSelectedIndex(3);
    }//GEN-LAST:event_btnTbProductActionPerformed

    private void btnTbAddProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTbAddProductActionPerformed
        // Navigate Add Product Tab 
        managerDashboard.setSelectedIndex(0);
    }//GEN-LAST:event_btnTbAddProductActionPerformed

    private void btnTbUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTbUserActionPerformed
        //Navigate User Tab
        managerDashboard.setSelectedIndex(1);
    }//GEN-LAST:event_btnTbUserActionPerformed

    private void btnTbProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTbProfileActionPerformed
        // Navigate User Profile Tab
        managerDashboard.setSelectedIndex(2);

    }//GEN-LAST:event_btnTbProfileActionPerformed

    private void btnViewTbAddProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewTbAddProductActionPerformed
        // In View Tab To Navigate Add Product Tab 
        managerDashboard.setSelectedIndex(1);
    }//GEN-LAST:event_btnViewTbAddProductActionPerformed

    private void btnCashierViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCashierViewActionPerformed
        // View Cashier Dashboard
        Cashier cashier = new Cashier();
        cashier.setVisible(true);
    }//GEN-LAST:event_btnCashierViewActionPerformed

    private void btnAddUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddUserActionPerformed

    }//GEN-LAST:event_btnAddUserActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        // Logout for navigate main Register Form
        RegisterForm logout = new RegisterForm();
        logout.setVisible(true);
        this.dispose(); //Close Current DashBoard
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // Logout for navigate main Register Form
        RegisterForm logout = new RegisterForm();
        logout.setVisible(true);
        this.dispose(); //Close Current DashBoard
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void addPrductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPrductActionPerformed
        // Check if the user is a manager before opening the product management form
        if (userService.isUserManager()) {
            crudProduct productForm = new crudProduct(userService, productService);
            productForm.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Only managers can access product management.", "Access Denied", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_addPrductActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagerForm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagerForm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagerForm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagerForm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                UserService userService = new UserService(new DatabaseManager());
                ProductService productService = new ProductService(new DatabaseManager());
                new ManagerForm(userService, productService).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MbackgroundPanel;
    private javax.swing.JPanel addMainPanel;
    private javax.swing.JButton addPrduct;
    private javax.swing.JButton addPrduct2;
    private javax.swing.JButton btnAddUser;
    private javax.swing.JButton btnCashierView;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnTbAddProduct;
    private javax.swing.JButton btnTbProduct;
    private javax.swing.JButton btnTbProfile;
    private javax.swing.JButton btnTbUser;
    private javax.swing.JButton btnViewTbAddProduct;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JPanel crudProductPanel;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblManageProduct;
    private javax.swing.JLabel lblManageUsers;
    private javax.swing.JLabel lblManageUsers1;
    private javax.swing.JLabel lblViewProductMain;
    private javax.swing.JTabbedPane managerDashboard;
    private javax.swing.JTable productTable;
    private javax.swing.JPanel profilePanel;
    private javax.swing.JButton removeProduct;
    private javax.swing.JPanel userMainPanel;
    private javax.swing.JPanel userMainPanel1;
    private javax.swing.JPanel userPanel;
    private javax.swing.JPanel viewMainPanel;
    private javax.swing.JPanel viewProductPanel;
    // End of variables declaration//GEN-END:variables
}
